name: Build .deeplink files

on:
  push:
    branches:
      - master
    paths:
      - '**.json'
  repository_dispatch:
    types: [trigger-routing-build]
  workflow_dispatch:
    inputs:
      message:
        description: 'Release message'
        required: false
        type: string
        default: 'Updated geofiles'
      mode:
        description: 'Routing mode'
        required: false
        type: choice
        options:
          - add
          - onadd
        default: 'onadd'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-slim

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout templates
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            /*.json
          sparse-checkout-cone-mode: false
          path: input

      - name: Make deeplinks
        run: |
          mkdir -p output
          for config in input/*.json; do
            sed -i "s/LAST_UPDATED/${EPOCHSECONDS}/" "$config"
            echo -n "happ://routing/${{ env.ROUTING_MODE }}/$(base64 -w 0 "$config")" > "output/$(basename "$config" .json).deeplink"
          done
          echo "happ://routing/off" > "output/disable.deeplink"
        env:
          ROUTING_MODE: ${{ inputs.mode || 'onadd' }}

      - name: Generate checksums
        run: cd output && sha256sum *.deeplink > checksums.txt

      - name: Set release tag
        run: echo "TAG_NAME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Release and upload assets
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: "${{ env.TAG_NAME }}"
          name: "${{ env.TAG_NAME }}"
          body: "${{ env.RELEASE_MESSAGE }}"
          prerelease: false
          draft: false
          working_directory: output
          files: |
            *.deeplink
            checksums.txt
          fail_on_unmatched_files: true
        env:
          RELEASE_MESSAGE: "${{
            inputs.message ||
            github.event.head_commit.message ||
            format('new geofiles release: {0}', github.event.client_payload.version) }}"
